# Generated by Django 4.2.8 on 2024-10-20 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='stockprice',
            name='unique_stock_price',
        ),
        migrations.RemoveIndex(
            model_name='stockprice',
            name='core_stockp_symbol_3194c4_idx',
        ),
    ]
