# Generated by Django 4.2.8 on 2024-10-20 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_stockprice_unique_stock_price_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='stockprice',
            index=models.Index(fields=['symbol', 'timestamp'], name='core_stockp_symbol_3194c4_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockprice',
            constraint=models.UniqueConstraint(fields=('symbol', 'timestamp'), name='unique_stock_price'),
        ),
    ]
